Repository ridi/select-frontend, pull requests merged in 2019-09, with the labels that each got.

#102 유저 로그인 처리 되고 나면 트래커에 정보 업데이트 하는 처리 추가.
  src/app/services/tracking/index.ts
  src/app/services/tracking/sagas.ts
  src/app/services/user/sagas.ts
Labels: hotfix

#98 테스트 수정
  jest.config.js
  jest.setup.js
  package.json
  src/app/utils/__tests__/stateHydrator.test.ts
  yarn.lock
Labels: chore

#113 .gitignore에 coverage 폴더 추가
  .gitignore
Labels: chore

#114 Fix section layout
  jest.config.js
  jest.setup.js
  package.json
  src/app/components/Home/HomeSpotlightSection.tsx
  src/app/components/Home/__tests__/HomeSpotlightSection.test.tsx
  src/app/components/InlineHorizontalBookList.tsx
  src/css/home/HomeSectionSpotlight.css
  yarn.lock
Labels: bug, chore

#116 홈화면 섹션 레이아웃 깨지는 것 수정.
  package.json
  src/css/home/HomeSectionSpotlight.css
  src/css/placeholder/HomePlaceholder.css
  yarn.lock
Labels: hotfix

#128 Feature/maintenance fix
  src/app/components/CompactPageHeader.tsx
  src/app/components/MaintenanceContext.tsx
  src/app/config/axios.ts
  src/app/scenes/ErrorPage.tsx
  src/app/services/serviceStatus/index.ts
  src/css/base/MaintenancePage.css
Labels: hotfix
